/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Tue Sep 27 12:17:09 2016. */

#include "reading.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ReadingMessage_fields[8] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, ReadingMessage, sensor, sensor, 0),
    PB_FIELD(  2, DOUBLE  , OPTIONAL, STATIC  , OTHER, ReadingMessage, value, sensor, 0),
    PB_FIELD(  3, INT64   , OPTIONAL, STATIC  , OTHER, ReadingMessage, average_over_seconds, value, 0),
    PB_FIELD(  4, DOUBLE  , OPTIONAL, STATIC  , OTHER, ReadingMessage, longitude, average_over_seconds, 0),
    PB_FIELD(  5, DOUBLE  , OPTIONAL, STATIC  , OTHER, ReadingMessage, latitude, longitude, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, ReadingMessage, unit, latitude, 0),
    PB_FIELD(  7, INT64   , OPTIONAL, STATIC  , OTHER, ReadingMessage, time, unit, 0),
    PB_LAST_FIELD
};

const pb_field_t ReadingGroupMessage_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, ReadingGroupMessage, readings, readings, &ReadingMessage_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ReadingGroupMessage, readings[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ReadingMessage_ReadingGroupMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ReadingGroupMessage, readings[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ReadingMessage_ReadingGroupMessage)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
